sudo: false
language: python
python:
    - 3.5
env:
    - TOXENV=py35
install:
    - pip install -U pip
    - pip install -U setuptools
    - pip install tox
    - pip install coveralls
script:
    - tox
after_success:
    - coveralls
